name: py37
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - neuralcoref
  - spacy=2.1
  - pandas
  - python=3.7
  - pyvis
  - joblib
  - pip:
    - networkx
    - python-louvain
    - streamlit
    - streamlit-agraph